### PR TITLE
Add option to measure time in milliseconds to input

### PR DESCRIPTION
**Pull request by MarkelZ**
Previously, the `Input` class only allowed measuring the number of frames for which a key is pressed.

I added an optional argument to the update call `update(self, deltaTime=1)`, so that the time elapsed between the last frames can be passed. This is very common in most game engines. It allows determining things like "Has key X been pressed for over Y milliseconds?".

If the user does not specify `deltaTime` it defaults to 1, so it will measure the number of frames instead. Therefore, we still have the original functionality.

### CODE REVIEW

**Review by rik-cross — APPROVED** [review]

**Comment by rik-cross** [comment]
@MarkelZ thank you so much for this -- I agree this is an improvement!

**Comment by rik-cross** [comment]
@MarkelZ Just a thought, but a default longPressDuration of 1000 and a default deltaTime of 1 means the default long press duration is quite long. I quite like the idea of the library working well 'out-of-the-box' as much as possible. What do you think -- should we tweak the defaults? Thanks!

**Comment by MarkelZ** [comment]
Nice to see that you like my changes! Yep you're right, the long press duration is defaulted to 1000 with milliseconds in mind instead of frames. Since by default `Input` measures frames instead of milliseconds, I think it would be good to adjust the default long press duration, maybe to something like 60 as was done originally. Does it sound good to you?

**Comment by MarkelZ** [comment]
@rik-cross Nice to see that you like my changes! Yep you're right, the long press duration is defaulted to 1000 with milliseconds in mind instead of frames. Since by default `Input` measures frames instead of milliseconds, I think it would be good to adjust the default long press duration, maybe to something like 60 as was done originally. Does it sound good to you?

**Comment by rik-cross** [comment]
Perfect, yes I'll change that now. Thanks again!

**Pull request merged**
